### ISSUE TITLE
[Feature Request] HDD unlocker

### ISSUE THREAD

**Issue by LuanTeles** [Evilnat/xai_plugin#11]
Following https://www.psx-place.com/threads/ps3-unlock-hdd-space.33551/ the hdd reserved space unlocker and the implementation of this in webMAN MOD https://github.com/aldostools/webMAN-MOD/search?q=unlock+hdd

would be nice to have it straight from xai and out of the box in your firmwares

**Comment by Evilnat** [comment]
Done mate! It will unlock/restore 8% of internal HDD space
![screenshot_2022_11_22_10_40_25](https://user-images.githubusercontent.com/560108/203409212-089ce943-9485-497c-8662-5ea9e62a140c.png)
