### ISSUE TITLE
[Feature Improvement] Spoof IDPS/PSID from internal hdd

### ISSUE THREAD

**Issue by LuanTeles** [Evilnat/xai_plugin#13]
I saw the new feature to spoof via dev_usb/IDPS.txt and PSID.txt, i would like to request support for internal hdd too, so we can just ftp it or install via pkg a valid IDPS/PSID without the need of a USB drive

**Comment by Evilnat** [comment]
Done mate, now xai_plugin will find the following files:

**HDD:** _/dev_hdd0/tmp/IDPS.txt_ - _/dev_hdd0/tmp/PSID.txt_
**USB:** _/dev_usbXXX/PSID.txt_ - _/dev_usbXXX/IDPS.txt_

**Comment by LuanTeles** [comment]
Thanks Nat
