### ISSUE TITLE
[Feature Improvement] Show IP address in FTP Menu

### ISSUE THREAD

**Issue by LuanTeles** [Evilnat/xai_plugin#14]
I think when the ftp option is enabled a popup saying LISTENING FROM XXX.XXX.XXX.X could be displayed or an option in the same XMBML menu could display the IP address

**Comment by Evilnat** [comment]
Done mate, I have implemented it
![screenshot_2022_11_22_07_45_31](https://user-images.githubusercontent.com/560108/203405848-d77e5a1b-2244-4325-ba76-fd0bd7775c06.png)
