### ISSUE TITLE
Add Option to show IP address in XMB

### ISSUE THREAD

**Issue by ZweiBR** [Evilnat/xai_plugin#17]
Would it be possible to implement a xai command to show a popup with the IP address of the system? same as the FTP option, but as a standalone, it can be useful to use with other plugins and homebrews for a quick check

You can add it to complete system information items

**Comment by Evilnat** [comment]
I have added it mate, I need to test it, it will swap current xmb_plugin.srpx from DEX

**Comment by Evilnat** [comment]
Added mate ;)
