### ISSUE TITLE
[Feature Request] Startup Time

### ISSUE THREAD

**Issue by LuanTeles** [Evilnat/xai_plugin#18]
Can an option to display the system running time be added? I mean the running time since startup?

And an option to display the system age or total running time ( i don't know how to name it hhaha), just like webman mod

![image](https://user-images.githubusercontent.com/110236244/203472304-fb6e250e-a45d-4d3c-a2df-63a2dc135b90.png)

**Comment by Evilnat** [comment]
I will take a look

**Comment by LuanTeles** [comment]
Already Added.

Thanks
