### ISSUE TITLE
[Feature Request] Auto-enable FTP server on boot

### ISSUE THREAD

**Issue by mpaterakis** [Evilnat/xai_plugin#26]
Coming from X360's Aurora, I am used to having the server automatically enabled as soon as the console boots. It would be great to have the option for it on Evilnat CFWs as well!

Is there a manual way to do that as it stands? I looked into all the menus of Evilnat's CFW but couldn't find such an option.

**Comment by nikolaevich23** [comment]
Add this line in \dev_hdd0\boot_plugins.txt:
`/dev_blind/vsh/module/ftp.sprx`

or install [Webman-MOD](https://github.com/aldostools/webMAN-MOD/releases/tag/1.47.45)

**Comment by mpaterakis** [comment]
Thank you! I wanted to use the default EVILNAT ftp server as I was having problems with WebMM's FTP.
