### ISSUE TITLE
[Feature Request] LED/Beep Control

### ISSUE THREAD

**Issue by LuanTeles** [Evilnat/xai_plugin#4]
Can misys' xai plugin LED/Beep control be added?

**Comment by Evilnat** [comment]
Working on it

**Comment by Evilnat** [comment]
Done, I have added some modes in xai_plugin under "Basic Tools > Led Tools". Would you like to try it with a PKG?

**Comment by LuanTeles** [comment]
Thank you NAT, glad to see you back =)

By Beep control, i meant buzz ringer, not really important just to test it, one beep, double beeps and etc.

That feature is present on webMAN MOD and one of misys' xai_plugin, i just mentioned it, because having all features in just one xai would be ideal.

**Comment by Evilnat** [comment]
Done! I have added it to xai_plugin and is working fine. I will make a PKG and send it to you as soon as I can

**Comment by LuanTeles** [comment]
Thank you
