### ISSUE TITLE
[Feature Request] Overclock Features

### ISSUE THREAD

**Issue by LuanTeles** [Evilnat/xai_plugin#9]
I would like to request Overclock features via xai plugin.

**Comment by LuanTeles** [comment]
RSX Clock
650
675
700
725
750
775

**Comment by Evilnat** [comment]
It would be great but I couldn't overclock through xai_plugin, LV1 reboots all changes. I need to research a bit more

**Comment by Evilnat** [comment]
Impossible mate, LV1 restarts itself every time the PS3 is rebooted, it need to be added hardly coded in the CFW itself

**Comment by LuanTeles** [comment]
> Impossible mate, LV1 restarts itself every time the PS3 is rebooted, it need to be added hardly coded in the CFW itself

Even cobra can't patch it on boot? or the values are read even before that?

**Comment by Evilnat** [comment]
No, we need to patch it even before Cobra and LV2, and it is impossible, LV1 loads before both of them

**Comment by LuanTeles** [comment]
That's sad news, if we only could get it as the overclock features works on PSP/PSV would be awesome.

An alternative would be unpack/patche/repack the COREOS, but would be risk
